# Generated by Django 4.0.4 on 2022-05-05 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_customer_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderedItem',
            new_name='OrderItem',
        ),
    ]
